// Generated by LiveScript 1.2.0
var fs, request, data, chk, fetch;
fs = require('fs');
request = require('request');
data = JSON.parse(fs.readFileSync('starbucks.json').toString());
chk = {};
fetch = function(list){
  var item;
  if (list.length === 0) {
    fs.writeFileSync('count.json', JSON.stringify(chk));
    console.log('done');
    return;
  }
  item = list.splice(0, 1)[0];
  if (!item) {
    console.log(item);
    console.log(list);
    return;
  }
  if (!item.id) {
    console.log(item);
    setTimeout(function(){
      return fetch(list);
    }, 0);
    return;
  }
  return request({
    url: "http://graph.facebook.com/" + item.id,
    method: 'GET'
  }, function(e, r, b){
    var c;
    c = JSON.parse(b);
    console.log(item.name, item.id, c.checkins);
    chk[item.id] = c.checkins;
    return setTimeout(function(){
      return fetch(list);
    }, 0);
  });
};
fetch(data.data);